version: "3"

services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  web:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mysqldb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db: